spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:ims_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Data@1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET:R2V0TWVWZXJ5TG9uZ0tleUZvckVNU0FwcGxpY2F0aW9uTGlrZVZlcnlMb25n}
  expirationMs: 86400000