spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/ims_auth
    username: postgres
    password: Data@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

jwt:
  secret: R2V0TWVWZXJ5TG9uZ0tleUZvckVNU0FwcGxpY2F0aW9uTGlrZVZlcnlMb25n
  expirationMs: 86400000